# action.yml
name: 'Build STM32 Cmake project'
description: 'Build STM32 Cmake project'
inputs:
  project-path:  # id of input
    description: 'Path to source code root'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project-path }}
